- Links:
    - Google:
        - abbr: GO
          href: https://www.google.com
    - ChatGPT:
        - abbr: AI
          href: https://chatgpt.com
    - GitHub:
        - abbr: GH
          href: https://github.com