- Infrastructure:
    - Homepage Docs:
        href: https://gethomepage.dev
        description: Uradna dokumentacija
    - Coolify:
        href: https://coolify.io
        description: Deployment platforma

- Tools:
    - GitHub:
        href: https://github.com
        description: Git repozitoriji